travis:
  secure:
    BINSTAR_TOKEN: GhHWnB6tIYguxgatD3eiPI05slIgHfmuNX3RlOjNjdTaob2Ls1mnw5dhHo7FxLc8od44IPqNAjoa/DUZyExUkuUx6WtKe3Q+qyOiHYxJOX75ecpM3ySyCz/5maEHZYnOWyuNcwcP/5z+7yaJImHkFTgCLMCWpC/td7ePEiYrOemduoqioS1l/X0h21tVwJTes0+zjQ6fNH3EVciFPG2+qDIpHI1VL7TgURpFsgjRN/6/WJYhZAL7Ama5oVbujOqMUdLyKYcgo1JBMbhbfIuLXRyVVFzI1h+4II4G3A6dOd7FHGhFfP6tejIZVYK3qoXdDb3ksL9Mjynju7wGnmrO/5LrzYYKDncdMUZ3djilk0GpPlVvDNuf9DV1jisXiFXkuhH5cHJI/0CZYoP6DsGo+yq4dZcQIwcbwy3SeYcd7Bx4vWtOyHtmq42vnne1k0QtVBNhalYdsA2G2DvBS2m3onCXDNp1PCII5twrr8/jsKQs4YgK1+rgpRmaoVaj9NUoey9wcLgg5P4MaNKIPaq+fe2BR8Nrv5MRIHbf9EpBMmsJodSDOZQnFP7bt8dBQ6V6duqR2yuWcoSWHt+7K6F8D74gqiuoaOBH2D/JS+wCdZNlVk9DzTJgCWHpguBk8HScwbW0b5TJ/MIOTXjR1ipZBhj3NdNfNATYmKDzFmhKdiM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
